#### 1. Import the numpy package under the name `np` (★☆☆)

#### 2. Print the numpy version and the configuration (★☆☆)

#### 3. Create a null vector of size 10 (★☆☆)

#### 4. How to find the memory size of any array (★☆☆)

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

#### 8. Reverse a vector (first element becomes last) (★☆☆)

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

#### 11. Create a 3x3 identity matrix (★☆☆)

#### 12. Create a 3x3x3 array with random values (★☆☆)

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

#### 17. What is the result of the following expression? (★☆☆)

In [1]:
import numpy as np

In [7]:
print(np.show_config)

<function show at 0x7f85b45ab940>


In [5]:
ceros = np.zeros(10)
print(ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [14]:
ceross = np.zeros((10,10))
size = (ceross.size) #cantidad de elementos del arreglo 
print(size)
itemsize = (ceross.itemsize) #tamanio en bytes de un arreglo.
print(itemsize)
print('El tamanio en bytes es de:' ,size * itemsize) 


100
8
El tamanio en bytes es de: 800


In [18]:
valores = np.zeros(10)
valores[4] = 1

In [19]:
valores

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

 7. Create a vector with values ranging from 10 to 49 (★☆☆)


In [21]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)


In [25]:

print(np.flip(Z)) 
#flip es la funcion que lo da vuelta

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)


In [27]:
matriz = np.arange(0,9).reshape(3,3)
matriz

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)


In [37]:
non_zero = np.nonzero([1,2,0,0,4,0])
non_zero #nonzero devuelve los indices de los elementos que son 0

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)


In [39]:
id = np.eye(3)
id 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)


In [47]:
random = np.random.rand(3,3)
random

array([[0.43224869, 0.76841952, 0.7666088 ],
       [0.36092656, 0.2132769 , 0.68819453],
       [0.88532584, 0.15351768, 0.81982747]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)


In [52]:
x = np.random.rand(10,10)
print(x)
print(np.min(x))
print(np.max(x))


[[0.09320162 0.72778034 0.54819752 0.28646032 0.39562021 0.78665638
  0.18148011 0.40625188 0.7283596  0.19589898]
 [0.56024435 0.75925105 0.94421368 0.74833537 0.59867437 0.37195502
  0.51757807 0.1279949  0.56352511 0.81018772]
 [0.34480441 0.98411456 0.52143769 0.36164859 0.81045793 0.94132826
  0.10031235 0.98517196 0.02146939 0.9916586 ]
 [0.01941922 0.05430737 0.00172467 0.12110264 0.08739366 0.88754251
  0.22920128 0.77347198 0.77860369 0.88283883]
 [0.28409712 0.15080601 0.43952678 0.26557616 0.46335973 0.46177969
  0.09432442 0.22099355 0.43876383 0.42577127]
 [0.04258308 0.83215333 0.23178265 0.51113944 0.63298344 0.19738718
  0.16123927 0.47206499 0.24319679 0.12205437]
 [0.20308346 0.70984145 0.47809895 0.93988896 0.31885747 0.04622243
  0.75942262 0.48419114 0.39765873 0.24361457]
 [0.85896233 0.78278348 0.41213342 0.59597613 0.56164294 0.25983746
  0.98582412 0.91241386 0.28507981 0.76434881]
 [0.54297463 0.33611348 0.8848312  0.50595487 0.18063654 0.01988716
  0.99520039

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)


In [59]:
m = np.random.rand(30)
print(m)
print(np.mean(m))

[0.61344411 0.89362617 0.33288232 0.50207044 0.31015262 0.93115919
 0.33062729 0.66208041 0.39258369 0.1654562  0.4807056  0.15402416
 0.8986975  0.26817986 0.75379245 0.30741281 0.54386325 0.38600133
 0.45433142 0.30834538 0.9228166  0.85087262 0.81663841 0.69788071
 0.1286608  0.04646268 0.45804142 0.41288964 0.11138246 0.56121563]
0.48987657195998763
